name: templete_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  cupertino_icons:
  flutter:
    sdk: flutter

  # Riverpod.
  flutter_riverpod: 2.4.5
  riverpod_annotation:

  # Entity.
  json_annotation:
  freezed_annotation:

  # Firebase.
  firebase_core: 2.22.0
  firebase_analytics:
  cloud_firestore:
  firebase_auth:
  cloud_functions:
  firebase_crashlytics:

  # Widget.
  gap:  

  # Info.
  package_info_plus:
  device_info_plus:

  # Other.
  change_app_package_name:
  intl:
  roggle:
  url_launcher:

dev_dependencies:  
  flutter_test:
    sdk: flutter

  # Static analysis.
  custom_lint:  
  pedantic_mono:
  riverpod_lint:

  # Code generation.
  build_runner:
  freezed:
  json_serializable:  
  riverpod_generator:

  # Other.
  flutter_launcher_icons:


# flutter_gen:
#   output: lib/core/res/gen/
#   colors:
#     inputs:
#       - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # カスタムフォントを利用する場合はここを設定する
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
# flutter_launcher_iconsを利用してアイコンのリサイズする場合はここを設定する
#flutter_icons:
#  android: true
#  ios: true
#  image_path_android: "assets/icon/icon_android.png"
#  image_path_ios: "assets/icon/icon_ios.png"
#  adaptive_icon_foreground: "assets/icon/adaptive_icon_foreground.png"
#  adaptive_icon_background: "#F4A281"

