name: template_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  cupertino_icons:
  flutter:
    sdk: flutter

  # Riverpod.
  flutter_riverpod: 2.4.5
  riverpod_annotation:

  # Entity.
  json_annotation:
  freezed_annotation:

  # Routing.
  auto_route: ^7.8.3

  # Firebase.
  firebase_core: 2.22.0
  firebase_analytics:
  cloud_firestore:
  firebase_auth:
  cloud_functions:
  firebase_crashlytics:

  # Widget.
  gap:  

  # Info.
  package_info_plus:
  device_info_plus:

  # Debug.
  roggle:
  device_preview:

  # Other.
  change_app_package_name:
  flutter_localizations:
    sdk: flutter
  intl:
  universal_html:
  url_launcher:
  version:

dev_dependencies:  
  flutter_test:
    sdk: flutter

  # Static analysis.
  custom_lint:  
  pedantic_mono:
  riverpod_lint:

  # Code generation.
  auto_route_generator: ^7.3.1
  build_runner:
  freezed:
  json_serializable:  
  riverpod_generator:

  # Other.
  flutter_launcher_icons:


# flutter_gen:
#   output: lib/core/res/gen/
#   colors:
#     inputs:
#       - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  fonts:
    - family: LINESeedJP
      fonts:
        - asset: assets/fonts/LINESeedJP_A_OTF_Th.otf
          weight: 100
        - asset: assets/fonts/LINESeedJP_A_OTF_Rg.otf
          weight: 400
        - asset: assets/fonts/LINESeedJP_A_OTF_Bd.otf
          weight: 700
        - asset: assets/fonts/LINESeedJP_A_OTF_Eb.otf
          weight: 800

# flutter_launcher_iconsを利用してアイコンのリサイズする場合はここを設定する
#flutter_icons:
#  android: true
#  ios: true
#  image_path_android: "assets/icon/icon_android.png"
#  image_path_ios: "assets/icon/icon_ios.png"
#  adaptive_icon_foreground: "assets/icon/adaptive_icon_foreground.png"
#  adaptive_icon_background: "#F4A281"

