// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQUj8hov_sH-av1MZgcj81aJN4fanlVfQ',
    appId: '1:521399014343:web:cc3de3872dccbb8abcbfe2',
    messagingSenderId: '521399014343',
    projectId: 'toda-template-app-dev',
    authDomain: 'toda-template-app-dev.firebaseapp.com',
    storageBucket: 'toda-template-app-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdK6o-5aD32fBxq5QJA1HMygp4FyOsf8Q',
    appId: '1:521399014343:android:3fc077dcccab2c0fbcbfe2',
    messagingSenderId: '521399014343',
    projectId: 'toda-template-app-dev',
    storageBucket: 'toda-template-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTuegUxZwiU6bbZfEr3nRrtqzQS6vKl9I',
    appId: '1:521399014343:ios:d199dccde3051506bcbfe2',
    messagingSenderId: '521399014343',
    projectId: 'toda-template-app-dev',
    storageBucket: 'toda-template-app-dev.appspot.com',
    iosBundleId: 'com.toda.TemplateApp.dev',
  );
}
