// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBom6FzOb5gIDDGA9qaZLxTTMgmJCJnn8E',
    appId: '1:389752019580:web:3c02914c2b7de94c8e47f9',
    messagingSenderId: '389752019580',
    projectId: 'toda-templete-app-prod',
    authDomain: 'toda-templete-app-prod.firebaseapp.com',
    storageBucket: 'toda-templete-app-prod.appspot.com',
    measurementId: 'G-X1Z1DXGB93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA22LAwyfZWLy5EjuGMM4wS1Ifdh0MjtG8',
    appId: '1:389752019580:android:97e24d0fe81a56b28e47f9',
    messagingSenderId: '389752019580',
    projectId: 'toda-templete-app-prod',
    storageBucket: 'toda-templete-app-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKizRF8CGwO_WN_kOe9ExCrjlZlEfO-a8',
    appId: '1:389752019580:ios:b0cccd6e817d93c28e47f9',
    messagingSenderId: '389752019580',
    projectId: 'toda-templete-app-prod',
    storageBucket: 'toda-templete-app-prod.appspot.com',
    iosBundleId: 'TempleteApp',
  );
}
