// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1iIMoMrvjHRbDYsWbBzVPQXQYK72V7Us',
    appId: '1:1063447347632:web:b245a8655743a584139675',
    messagingSenderId: '1063447347632',
    projectId: 'toda-template-app-prod',
    authDomain: 'toda-template-app-prod.firebaseapp.com',
    storageBucket: 'toda-template-app-prod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfGZyeOjIwDaXzXd1jsq8buju7h6TRyYg',
    appId: '1:1063447347632:android:2c4b8839eefa9674139675',
    messagingSenderId: '1063447347632',
    projectId: 'toda-template-app-prod',
    storageBucket: 'toda-template-app-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYd7qAYh0xXusiOLb_wmkQfUMVZg3Frfs',
    appId: '1:1063447347632:ios:5501b7780f66adbf139675',
    messagingSenderId: '1063447347632',
    projectId: 'toda-template-app-prod',
    storageBucket: 'toda-template-app-prod.appspot.com',
    iosBundleId: 'com.toda.TemplateApp',
  );
}
