// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsvo7u99BMwWi3AAUZmegRGoYGAGZnJVk',
    appId: '1:964480104378:web:79cbc2f24a727b5fec4f83',
    messagingSenderId: '964480104378',
    projectId: 'toda-templete-app-dev',
    authDomain: 'toda-templete-app-dev.firebaseapp.com',
    storageBucket: 'toda-templete-app-dev.appspot.com',
    measurementId: 'G-JR4Z8HZ5VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZUyuuLZVvAWhWLXu3jxMxhHoErUzclKc',
    appId: '1:964480104378:android:23f27044292f22a9ec4f83',
    messagingSenderId: '964480104378',
    projectId: 'toda-templete-app-dev',
    storageBucket: 'toda-templete-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwhR7t_46w3tfrcplXFO7VQ14MwHwpHbk',
    appId: '1:964480104378:ios:1fa0b29f31b39fdbec4f83',
    messagingSenderId: '964480104378',
    projectId: 'toda-templete-app-dev',
    storageBucket: 'toda-templete-app-dev.appspot.com',
    iosBundleId: 'TempleteApp.dev',
  );
}
